name: synapse

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    run: flutter analyze
    exec:
      concurrency: 1
    description: Run `flutter analyze` in every package.

  format:
    run: dart format .
    description: Format all Dart code.

  test:
    run: flutter test
    exec:
      concurrency: 1
    description: Run tests in every package that has them.

  build:web:
    run: flutter build web --release
    packageFilters:
      scope: synapse_app
    description: Build the web release of the app.
