import 'package:synapse_core/synapse_core.dart';

/// The seed Disease Bank (prompt 45). Each disease is Concept-anchored and
/// cross-links to drugs, labs, ECG, sounds and algorithms. Educational content.
class DiseasesSeed {
  const DiseasesSeed._();

  /// New concept nodes these diseases anchor to (merged by the repository).
  static const List<Concept> concepts = [
    Concept(id: 'c_chf', name: 'Heart failure', aliases: ['CHF', 'congestive heart failure'], domain: ConceptDomain.cardiology, summary: 'Impaired cardiac output / filling causing congestion and fatigue.'),
    Concept(id: 'c_cap', name: 'Community-acquired pneumonia', aliases: ['CAP', 'pneumonia'], domain: ConceptDomain.clinical, summary: 'Acute lower-respiratory infection acquired outside hospital.'),
    Concept(id: 'c_asthma', name: 'Asthma', domain: ConceptDomain.clinical, summary: 'Reversible airway obstruction with bronchial hyperresponsiveness.'),
    Concept(id: 'c_copd', name: 'COPD', aliases: ['chronic obstructive pulmonary disease', 'emphysema'], domain: ConceptDomain.clinical, summary: 'Progressive, largely irreversible airflow limitation.'),
    Concept(id: 'c_t2dm', name: 'Type 2 diabetes', aliases: ['T2DM', 'diabetes mellitus'], domain: ConceptDomain.endocrine, summary: 'Insulin resistance with relative insulin deficiency.'),
    Concept(id: 'c_stroke', name: 'Ischemic stroke', aliases: ['CVA', 'brain attack'], domain: ConceptDomain.neurology, summary: 'Acute focal neurologic deficit from cerebral ischemia.'),
    Concept(id: 'c_pe', name: 'Pulmonary embolism', aliases: ['PE', 'pulmonary embolus'], domain: ConceptDomain.clinical, summary: 'Occlusion of pulmonary arteries, usually by venous thrombus.'),
    Concept(id: 'c_htn', name: 'Hypertension', aliases: ['high blood pressure', 'HTN'], domain: ConceptDomain.cardiology, summary: 'Sustained elevation of arterial blood pressure.'),
    Concept(id: 'c_cirrhosis', name: 'Cirrhosis', domain: ConceptDomain.clinical, summary: 'End-stage hepatic fibrosis with portal hypertension.'),
  ];

  static final List<Disease> all = [
    Disease(
      id: 'd_afib',
      conceptId: 'c_afib',
      name: 'Atrial fibrillation',
      synonyms: ['AF', 'a-fib'],
      icd10: ['I48'],
      specialty: ['Cardiology'],
      system: BodySystem.cardiovascular,
      summary: 'A supraventricular tachyarrhythmia with uncoordinated atrial activation, producing an irregularly irregular ventricular response and loss of atrial kick.',
      epidemiology: 'Most common sustained arrhythmia; prevalence rises sharply with age (~10% over 80).',
      etiology: 'Hypertension, valvular disease, heart failure, hyperthyroidism, alcohol ("holiday heart"), sleep apnea, sepsis.',
      riskFactors: ['Age', 'Hypertension', 'Obesity', 'Alcohol', 'Hyperthyroidism', 'OSA'],
      pathophysiology: 'Ectopic foci (often pulmonary veins) and re-entrant circuits drive chaotic atrial depolarization at 400–600/min; the AV node filters conduction irregularly.',
      presentation: Presentation(
        symptoms: ['Palpitations', 'Dyspnea', 'Fatigue', 'Lightheadedness', 'Chest discomfort'],
        signs: ['Irregularly irregular pulse', 'Variable S1 intensity', 'Pulse deficit'],
      ),
      redFlags: ['Hemodynamic instability', 'Acute chest pain', 'Signs of stroke'],
      workup: Workup(labs: ['TSH', 'Electrolytes', 'CBC'], imaging: ['Echocardiogram'], ecg: 'c_afib'),
      differentials: ['d_aflutter', 'd_mat'],
      criteria: ['Irregularly irregular rhythm', 'Absent P waves', 'Fibrillatory baseline'],
      management: Management(
        conservative: ['Risk-factor modification', 'Reduce alcohol', 'Treat OSA'],
        medical: ['Rate control (beta-blocker or diltiazem)', 'Anticoagulation by CHA₂DS₂-VASc', 'Rhythm control if symptomatic'],
        surgical: ['Catheter ablation', 'Cardioversion (if unstable: synchronized)'],
        drugIds: ['drug_metoprolol', 'drug_warfarin', 'drug_apixaban'],
        algorithmId: 'algo_chest_pain',
      ),
      prognosis: 'Good with rate/rhythm control + anticoagulation; main risk is cardioembolic stroke.',
      complications: ['Ischemic stroke', 'Heart failure', 'Tachycardia-induced cardiomyopathy'],
      prevention: 'Blood-pressure control, weight loss, alcohol moderation.',
      highYield: ['Use CHA₂DS₂-VASc to decide anticoagulation', 'Unstable AF → synchronized cardioversion', 'Rate vs rhythm control have similar mortality'],
      mnemonicIds: [],
      difficulty: 3,
      evidence: Evidence(
        citations: [Citation(title: '2023 ACC/AHA/ACCP/HRS AF Guideline', source: 'Circulation', year: 2024, type: CitationType.guideline)],
        levelOfEvidence: LevelOfEvidence.a,
        lastReviewed: null,
      ),
      review: ReviewState(status: ReviewStatus.approved, reviewerName: 'Editorial board'),
    ),
    Disease(
      id: 'd_stemi',
      conceptId: 'c_stemi',
      name: 'ST-elevation myocardial infarction',
      synonyms: ['STEMI', 'heart attack'],
      icd10: ['I21'],
      specialty: ['Cardiology', 'Emergency'],
      system: BodySystem.cardiovascular,
      summary: 'Acute transmural myocardial ischemia from complete coronary occlusion — a time-critical emergency requiring immediate reperfusion.',
      epidemiology: 'A leading cause of death worldwide; incidence rising in younger adults.',
      etiology: 'Atherosclerotic plaque rupture with thrombotic occlusion; rarely embolism, dissection, vasospasm.',
      riskFactors: ['Smoking', 'Diabetes', 'Hypertension', 'Hyperlipidemia', 'Family history'],
      pathophysiology: 'Plaque rupture exposes thrombogenic core → platelet aggregation and occlusive thrombus → transmural infarction and ST elevation in the affected territory.',
      presentation: Presentation(
        symptoms: ['Crushing chest pain', 'Radiation to arm/jaw', 'Diaphoresis', 'Dyspnea', 'Nausea'],
        signs: ['Distress', 'Diaphoresis', 'New S4/S3', 'Hypotension if large'],
      ),
      redFlags: ['Ongoing chest pain', 'Hemodynamic instability', 'New heart failure', 'Syncope'],
      workup: Workup(labs: ['Troponin', 'BMP', 'CBC', 'Lipids'], imaging: ['Coronary angiography', 'Echo'], ecg: 'c_stemi'),
      differentials: ['d_pe', 'd_aortic_dissection', 'd_pericarditis'],
      criteria: ['ST elevation ≥1mm in ≥2 contiguous leads', 'New LBBB with symptoms'],
      management: Management(
        conservative: ['MONA is adjunctive — reperfusion is the priority'],
        medical: ['Dual antiplatelet (aspirin + P2Y12)', 'Anticoagulation', 'High-intensity statin', 'Beta-blocker once stable'],
        surgical: ['Primary PCI < 90 min', 'Fibrinolysis if PCI unavailable < 120 min', 'CABG for select anatomy'],
        drugIds: ['drug_aspirin', 'drug_atorvastatin', 'drug_metoprolol'],
        algorithmId: 'algo_chest_pain',
      ),
      prognosis: 'Strongly time-dependent: "time is muscle." Early reperfusion dramatically improves survival.',
      complications: ['Arrhythmia', 'Cardiogenic shock', 'Mechanical complications', 'Heart failure'],
      prevention: 'Statins, BP/glycemic control, smoking cessation.',
      highYield: ['Door-to-balloon < 90 minutes', 'Posterior MI: ST depression V1–V3', 'Right-sided ECG for inferior MI'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: '2023 ESC ACS Guideline', source: 'Eur Heart J', year: 2023, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_chf',
      conceptId: 'c_chf',
      name: 'Heart failure',
      synonyms: ['CHF', 'congestive heart failure'],
      icd10: ['I50'],
      specialty: ['Cardiology'],
      system: BodySystem.cardiovascular,
      summary: 'A clinical syndrome of impaired cardiac output or filling pressures, classified by ejection fraction (HFrEF vs HFpEF).',
      etiology: 'Ischemic heart disease, hypertension, valvular disease, cardiomyopathy.',
      riskFactors: ['CAD', 'Hypertension', 'Diabetes', 'Prior MI'],
      pathophysiology: 'Neurohormonal activation (RAAS, sympathetic) initially compensates but drives remodeling, congestion and progressive dysfunction.',
      presentation: Presentation(
        symptoms: ['Dyspnea on exertion', 'Orthopnea', 'PND', 'Fatigue', 'Leg swelling'],
        signs: ['Elevated JVP', 'S3 gallop', 'Bibasilar crackles', 'Peripheral edema'],
      ),
      redFlags: ['Resting dyspnea', 'Hypotension', 'Hypoxia'],
      workup: Workup(labs: ['BNP/NT-proBNP', 'BMP', 'CBC'], imaging: ['Echo', 'Chest X-ray'], sounds: 'c_s3'),
      differentials: ['d_copd', 'd_pe'],
      management: Management(
        conservative: ['Sodium/fluid restriction', 'Daily weights', 'Cardiac rehab'],
        medical: ['GDMT: ARNI/ACEi', 'Beta-blocker', 'MRA', 'SGLT2 inhibitor', 'Loop diuretic for congestion'],
        drugIds: ['drug_furosemide', 'drug_lisinopril', 'drug_metoprolol'],
      ),
      prognosis: 'Guideline-directed therapy markedly improves survival in HFrEF.',
      complications: ['Arrhythmia', 'Renal dysfunction', 'Sudden cardiac death'],
      highYield: ['S3 is specific for failure', 'The four pillars of HFrEF therapy', 'BNP helps distinguish cardiac vs pulmonary dyspnea'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: '2022 AHA/ACC/HFSA HF Guideline', source: 'JACC', year: 2022, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_cap',
      conceptId: 'c_cap',
      name: 'Community-acquired pneumonia',
      synonyms: ['CAP'],
      icd10: ['J18'],
      specialty: ['Pulmonology', 'Infectious disease'],
      system: BodySystem.respiratory,
      summary: 'Acute infection of the lung parenchyma acquired outside the hospital; S. pneumoniae is the classic pathogen.',
      etiology: 'Streptococcus pneumoniae, atypicals (Mycoplasma, Legionella), viral.',
      riskFactors: ['Age extremes', 'Smoking', 'COPD', 'Immunosuppression', 'Aspiration'],
      pathophysiology: 'Pathogen reaches alveoli, overwhelms defenses → inflammatory consolidation impairing gas exchange.',
      presentation: Presentation(
        symptoms: ['Productive cough', 'Fever', 'Pleuritic chest pain', 'Dyspnea'],
        signs: ['Crackles', 'Bronchial breath sounds', 'Dullness to percussion', 'Tachypnea'],
      ),
      redFlags: ['Hypoxia', 'Confusion', 'Hypotension (sepsis)'],
      workup: Workup(labs: ['CBC', 'CRP', 'Blood cultures if severe'], imaging: ['Chest X-ray'], sounds: 'c_crackles'),
      differentials: ['d_chf', 'd_pe', 'd_copd'],
      criteria: ['Use CURB-65 to triage severity and site of care'],
      management: Management(
        conservative: ['Hydration', 'Antipyretics', 'Oxygen if hypoxic'],
        medical: ['Outpatient: amoxicillin or a macrolide/doxycycline', 'Inpatient: beta-lactam + macrolide or respiratory fluoroquinolone'],
        drugIds: ['drug_amoxicillin', 'drug_azithromycin'],
        algorithmId: 'algo_dyspnea',
      ),
      prognosis: 'Most outpatients recover fully; severity scores guide escalation.',
      complications: ['Parapneumonic effusion', 'Empyema', 'Sepsis', 'ARDS'],
      highYield: ['CURB-65 ≥ 2 → consider admission', 'Cover atypicals', 'Reassess after 48–72h'],
      difficulty: 3,
      evidence: Evidence(citations: [Citation(title: 'ATS/IDSA CAP Guideline', source: 'AJRCCM', year: 2019, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_asthma',
      conceptId: 'c_asthma',
      name: 'Asthma',
      icd10: ['J45'],
      specialty: ['Pulmonology'],
      system: BodySystem.respiratory,
      summary: 'A chronic inflammatory airway disease with reversible obstruction and bronchial hyperresponsiveness.',
      etiology: 'Atopy, allergens, viral infection, exercise, cold air, irritants.',
      riskFactors: ['Atopy', 'Family history', 'Allergen exposure', 'Obesity'],
      pathophysiology: 'Th2-driven eosinophilic inflammation → bronchoconstriction, edema and mucus; reversible with bronchodilators.',
      presentation: Presentation(
        symptoms: ['Episodic wheeze', 'Cough (worse at night)', 'Chest tightness', 'Dyspnea'],
        signs: ['Expiratory wheeze', 'Prolonged expiration', 'Accessory muscle use in exacerbation'],
      ),
      redFlags: ['Silent chest', 'Exhaustion', 'SpO₂ < 92%', 'Inability to speak in sentences'],
      workup: Workup(labs: [], imaging: [], sounds: 'c_wheeze'),
      differentials: ['d_copd', 'd_chf'],
      criteria: ['Spirometry: obstructive pattern with ≥12% reversibility'],
      management: Management(
        conservative: ['Trigger avoidance', 'Inhaler technique', 'Action plan'],
        medical: ['Inhaled corticosteroid (controller)', 'SABA reliever', 'Step up with LABA/LAMA', 'Exacerbation: systemic steroids + nebulized bronchodilators'],
        drugIds: ['drug_albuterol', 'drug_prednisone'],
        algorithmId: 'algo_dyspnea',
      ),
      prognosis: 'Well-controlled with adherence; under-treatment risks fatal exacerbations.',
      complications: ['Status asthmaticus', 'Respiratory failure'],
      highYield: ['ICS is the cornerstone controller', 'A "quiet chest" is ominous', 'Reversibility distinguishes from COPD'],
      difficulty: 3,
      evidence: Evidence(citations: [Citation(title: 'GINA Strategy', source: 'GINA', year: 2024, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_copd',
      conceptId: 'c_copd',
      name: 'Chronic obstructive pulmonary disease',
      synonyms: ['COPD', 'emphysema', 'chronic bronchitis'],
      icd10: ['J44'],
      specialty: ['Pulmonology'],
      system: BodySystem.respiratory,
      summary: 'Progressive, largely irreversible airflow limitation from chronic airway inflammation and parenchymal destruction.',
      etiology: 'Tobacco smoke (dominant), biomass exposure, alpha-1 antitrypsin deficiency.',
      riskFactors: ['Smoking', 'Occupational dust', 'Air pollution', 'A1AT deficiency'],
      pathophysiology: 'Chronic irritant exposure → neutrophilic inflammation, mucus hypersecretion, and alveolar destruction → air trapping and V/Q mismatch.',
      presentation: Presentation(
        symptoms: ['Chronic productive cough', 'Progressive dyspnea', 'Wheeze'],
        signs: ['Barrel chest', 'Prolonged expiration', 'Distant breath sounds', 'Pursed-lip breathing'],
      ),
      redFlags: ['Acute hypercapnia', 'Altered mental status', 'Cor pulmonale'],
      workup: Workup(labs: ['ABG in exacerbation'], imaging: ['Chest X-ray'], sounds: 'c_wheeze'),
      differentials: ['d_asthma', 'd_chf'],
      criteria: ['Post-bronchodilator FEV1/FVC < 0.70'],
      management: Management(
        conservative: ['Smoking cessation (only intervention shown to slow decline)', 'Pulmonary rehab', 'Vaccination'],
        medical: ['LAMA ± LABA', 'ICS for frequent exacerbators', 'Exacerbation: steroids, bronchodilators, antibiotics if purulent'],
        drugIds: ['drug_albuterol', 'drug_prednisone'],
        algorithmId: 'algo_dyspnea',
      ),
      prognosis: 'Smoking cessation slows decline; exacerbations worsen trajectory.',
      complications: ['Respiratory failure', 'Pulmonary hypertension', 'Pneumothorax'],
      highYield: ['Smoking cessation is key', 'Target SpO₂ 88–92% to avoid CO₂ narcosis', 'Spirometry confirms diagnosis'],
      difficulty: 3,
      evidence: Evidence(citations: [Citation(title: 'GOLD Report', source: 'GOLD', year: 2024, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_aki',
      conceptId: 'c_aki',
      name: 'Acute kidney injury',
      synonyms: ['AKI'],
      icd10: ['N17'],
      specialty: ['Nephrology'],
      system: BodySystem.renal,
      summary: 'An abrupt decline in kidney function over hours–days, categorized as pre-renal, intrinsic, or post-renal.',
      etiology: 'Hypovolemia (pre-renal), ATN/glomerular (intrinsic), obstruction (post-renal).',
      riskFactors: ['CKD', 'Sepsis', 'Nephrotoxins', 'Contrast', 'Hypotension'],
      pathophysiology: 'Reduced perfusion, tubular injury, or obstruction reduces GFR → retention of nitrogenous waste and electrolyte disturbance.',
      presentation: Presentation(
        symptoms: ['Often asymptomatic', 'Oliguria', 'Edema', 'Confusion if uremic'],
        signs: ['Volume overload or depletion', 'Asterixis if uremic'],
      ),
      redFlags: ['Hyperkalemia with ECG changes', 'Severe acidosis', 'Anuria', 'Uremic pericarditis'],
      workup: Workup(labs: ['BMP', 'Urinalysis', 'FENa', 'Urine output'], imaging: ['Renal ultrasound']),
      differentials: ['d_chf'],
      criteria: ['KDIGO: ↑Cr ≥0.3 mg/dL in 48h, or 1.5× baseline, or urine < 0.5 mL/kg/h'],
      management: Management(
        conservative: ['Treat the cause', 'Optimize volume', 'Stop nephrotoxins', 'Adjust drug doses'],
        medical: ['Manage hyperkalemia/acidosis'],
        surgical: ['Relieve obstruction', 'Dialysis for refractory AEIOU indications'],
        drugIds: ['drug_furosemide'],
      ),
      prognosis: 'Pre-renal reverses with perfusion; ATN often recovers over weeks.',
      complications: ['Hyperkalemia', 'Metabolic acidosis', 'Volume overload', 'Uremia'],
      highYield: ['AEIOU dialysis indications', 'FENa <1% suggests pre-renal', 'Always check for obstruction'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'KDIGO AKI Guideline', source: 'Kidney Int', year: 2012, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.b),
    ),
    Disease(
      id: 'd_dka',
      conceptId: 'c_dka',
      name: 'Diabetic ketoacidosis',
      synonyms: ['DKA'],
      icd10: ['E11.1'],
      specialty: ['Endocrinology', 'Emergency'],
      system: BodySystem.endocrine,
      summary: 'A hyperglycemic emergency of insulin deficiency producing ketosis and a high-anion-gap metabolic acidosis.',
      etiology: 'Insulin omission, infection, MI, new-onset T1DM.',
      riskFactors: ['Type 1 diabetes', 'Infection', 'Non-adherence'],
      pathophysiology: 'Absolute insulin deficiency + counter-regulatory hormones → lipolysis and hepatic ketogenesis → ketoacidosis and osmotic diuresis.',
      presentation: Presentation(
        symptoms: ['Polyuria/polydipsia', 'Nausea/vomiting', 'Abdominal pain', 'Kussmaul breathing'],
        signs: ['Dehydration', 'Fruity breath', 'Tachycardia', 'Altered mentation'],
      ),
      redFlags: ['Severe acidosis', 'Altered consciousness', 'Hypokalemia'],
      workup: Workup(labs: ['Glucose', 'BMP + anion gap', 'Ketones', 'VBG'], imaging: []),
      differentials: ['d_aki'],
      criteria: ['Glucose >250', 'Anion-gap acidosis', 'Ketonemia/ketonuria'],
      management: Management(
        conservative: ['Find and treat the trigger', 'Hourly monitoring'],
        medical: ['IV fluids first', 'Insulin infusion', 'Replace potassium BEFORE insulin if low', 'Dextrose when glucose ~200'],
        drugIds: ['drug_insulin'],
        algorithmId: null,
      ),
      prognosis: 'Excellent with prompt treatment; mortality from delayed care or cerebral edema.',
      complications: ['Hypokalemia', 'Cerebral edema (children)', 'Hypoglycemia from treatment'],
      highYield: ['Fluids before insulin', 'Replace K+ before insulin if <3.3', 'Close the anion gap before stopping the drip'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'ADA Standards of Care', source: 'Diabetes Care', year: 2024, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_t2dm',
      conceptId: 'c_t2dm',
      name: 'Type 2 diabetes mellitus',
      synonyms: ['T2DM'],
      icd10: ['E11'],
      specialty: ['Endocrinology'],
      system: BodySystem.endocrine,
      summary: 'A chronic metabolic disorder of insulin resistance and progressive beta-cell dysfunction causing hyperglycemia.',
      etiology: 'Genetic predisposition + obesity/insulin resistance.',
      riskFactors: ['Obesity', 'Sedentary lifestyle', 'Family history', 'Metabolic syndrome'],
      pathophysiology: 'Peripheral insulin resistance with inadequate compensatory secretion → chronic hyperglycemia and micro/macrovascular damage.',
      presentation: Presentation(
        symptoms: ['Often asymptomatic', 'Polyuria', 'Polydipsia', 'Fatigue', 'Blurred vision'],
        signs: ['Acanthosis nigricans', 'Obesity', 'Slow-healing wounds'],
      ),
      redFlags: ['Marked hyperglycemia (HHS/DKA)', 'Diabetic foot infection'],
      workup: Workup(labs: ['HbA1c', 'Fasting glucose', 'Lipids', 'Urine albumin'], imaging: []),
      differentials: ['d_dka'],
      criteria: ['HbA1c ≥6.5%', 'Fasting glucose ≥126', 'Random ≥200 with symptoms'],
      management: Management(
        conservative: ['Diet and exercise', 'Weight loss', 'Diabetes education'],
        medical: ['Metformin first-line', 'Add SGLT2i / GLP-1 RA (cardio-renal benefit)', 'Individualized A1c target'],
        drugIds: ['drug_metformin', 'drug_insulin'],
      ),
      prognosis: 'Complications are largely preventable with glycemic and CV risk control.',
      complications: ['Retinopathy', 'Nephropathy', 'Neuropathy', 'CAD', 'Stroke'],
      highYield: ['Metformin first-line', 'SGLT2i/GLP-1 for CKD/CVD', 'Screen for complications annually'],
      difficulty: 3,
      evidence: Evidence(citations: [Citation(title: 'ADA Standards of Care', source: 'Diabetes Care', year: 2024, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_sepsis',
      conceptId: 'c_sepsis',
      name: 'Sepsis',
      icd10: ['A41'],
      specialty: ['Critical care', 'Infectious disease'],
      system: BodySystem.infectious,
      summary: 'Life-threatening organ dysfunction caused by a dysregulated host response to infection.',
      etiology: 'Any infection — pneumonia, UTI, intra-abdominal, skin, line infections.',
      riskFactors: ['Extremes of age', 'Immunosuppression', 'Indwelling devices', 'Chronic illness'],
      pathophysiology: 'Pathogen-triggered cytokine cascade → vasodilation, capillary leak, microvascular thrombosis and tissue hypoperfusion.',
      presentation: Presentation(
        symptoms: ['Fever or hypothermia', 'Confusion', 'Malaise'],
        signs: ['Tachycardia', 'Tachypnea', 'Hypotension', 'Mottled skin', 'Oliguria'],
      ),
      redFlags: ['Hypotension despite fluids (shock)', 'Lactate > 2', 'Altered mentation'],
      workup: Workup(labs: ['Lactate', 'Cultures', 'CBC', 'BMP'], imaging: ['Source imaging']),
      differentials: ['d_chf', 'd_pe'],
      criteria: ['qSOFA ≥2 flags risk', 'SOFA increase ≥2 defines organ dysfunction'],
      management: Management(
        conservative: ['Source control', 'Reassess perfusion'],
        medical: ['Broad-spectrum antibiotics within 1 hour', 'Crystalloid resuscitation', 'Vasopressors (norepinephrine) for refractory hypotension', 'Measure lactate'],
        drugIds: ['drug_piptazo', 'drug_vancomycin'],
      ),
      prognosis: 'Mortality rises with each hour of delayed antibiotics; early bundle saves lives.',
      complications: ['Septic shock', 'MODS', 'ARDS', 'DIC'],
      highYield: ['Antibiotics within 1 hour', 'qSOFA for rapid bedside screening', 'Norepinephrine is first-line pressor'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'Surviving Sepsis Campaign', source: 'Crit Care Med', year: 2021, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_stroke',
      conceptId: 'c_stroke',
      name: 'Acute ischemic stroke',
      synonyms: ['CVA', 'brain attack'],
      icd10: ['I63'],
      specialty: ['Neurology', 'Emergency'],
      system: BodySystem.neurology,
      summary: 'Sudden focal neurologic deficit from cerebral arterial occlusion — a time-critical emergency.',
      etiology: 'Large-artery atherosclerosis, cardioembolism (AF), small-vessel lacunes.',
      riskFactors: ['Hypertension', 'Atrial fibrillation', 'Diabetes', 'Smoking', 'Hyperlipidemia'],
      pathophysiology: 'Arterial occlusion → ischemic core with a salvageable penumbra; reperfusion time determines outcome.',
      presentation: Presentation(
        symptoms: ['Sudden weakness/numbness', 'Facial droop', 'Slurred speech', 'Vision loss'],
        signs: ['Focal deficit', 'Aphasia', 'Hemineglect', 'Gaze deviation'],
      ),
      redFlags: ['Time of onset (for thrombolysis window)', 'Decreased consciousness'],
      workup: Workup(labs: ['Glucose', 'Coags', 'CBC'], imaging: ['Non-contrast CT head (rule out bleed)', 'CT angiography']),
      differentials: ['d_dka'],
      criteria: ['NIHSS quantifies severity', 'Exclude hemorrhage before thrombolysis'],
      management: Management(
        conservative: ['Stroke unit care', 'Permissive hypertension acutely', 'Swallow screen'],
        medical: ['IV thrombolysis (tPA) within 4.5h if eligible', 'Aspirin after 24h', 'Secondary prevention: statin, BP, anticoagulation if AF'],
        surgical: ['Mechanical thrombectomy for large-vessel occlusion'],
        drugIds: ['drug_aspirin', 'drug_atorvastatin'],
      ),
      prognosis: 'Outcome is highly time-dependent — "time is brain."',
      complications: ['Hemorrhagic transformation', 'Cerebral edema', 'Aspiration pneumonia'],
      highYield: ['CT first to exclude bleed', 'tPA window 4.5h', 'BE-FAST recognition'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'AHA/ASA Stroke Guideline', source: 'Stroke', year: 2019, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_pe',
      conceptId: 'c_pe',
      name: 'Pulmonary embolism',
      synonyms: ['PE'],
      icd10: ['I26'],
      specialty: ['Pulmonology', 'Emergency'],
      system: BodySystem.respiratory,
      summary: 'Occlusion of the pulmonary arterial tree, usually by thrombus from a deep vein, causing V/Q mismatch and possible RV strain.',
      etiology: 'Venous thromboembolism from DVT; Virchow triad.',
      riskFactors: ['Immobility', 'Surgery', 'Malignancy', 'OCP/pregnancy', 'Prior VTE', 'Thrombophilia'],
      pathophysiology: 'Thrombus lodges in pulmonary arteries → dead-space ventilation, hypoxemia, and acute RV pressure overload.',
      presentation: Presentation(
        symptoms: ['Sudden dyspnea', 'Pleuritic chest pain', 'Hemoptysis', 'Syncope'],
        signs: ['Tachycardia', 'Tachypnea', 'Hypoxia', 'Signs of DVT'],
      ),
      redFlags: ['Hypotension (massive PE)', 'Syncope', 'Severe hypoxia'],
      workup: Workup(labs: ['D-dimer (if low pretest)', 'Troponin/BNP for risk'], imaging: ['CT pulmonary angiography'], ecg: 'c_afib'),
      differentials: ['d_stemi', 'd_cap', 'd_chf'],
      criteria: ['Use Wells score to set pretest probability', 'PERC to rule out in low-risk'],
      management: Management(
        conservative: ['Risk stratify (sPESI)'],
        medical: ['Anticoagulation (DOAC or heparin)', 'Thrombolysis for massive PE with shock'],
        surgical: ['Embolectomy / catheter therapy for select cases', 'IVC filter if anticoagulation contraindicated'],
        drugIds: ['drug_apixaban', 'drug_warfarin'],
        algorithmId: 'algo_chest_pain',
      ),
      prognosis: 'Good with prompt anticoagulation; massive PE carries high mortality.',
      complications: ['Obstructive shock', 'Chronic thromboembolic pulmonary hypertension'],
      highYield: ['Wells + D-dimer pathway', 'S1Q3T3 is classic but insensitive', 'Massive PE + shock → thrombolysis'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'ESC PE Guideline', source: 'Eur Heart J', year: 2019, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_htn',
      conceptId: 'c_htn',
      name: 'Hypertension',
      synonyms: ['high blood pressure', 'HTN'],
      icd10: ['I10'],
      specialty: ['Cardiology', 'Primary care'],
      system: BodySystem.cardiovascular,
      summary: 'Chronically elevated arterial pressure — a leading modifiable risk factor for stroke, MI, heart failure and CKD.',
      etiology: 'Primary (essential) in ~90%; secondary causes include renal, endocrine, OSA.',
      riskFactors: ['Age', 'Obesity', 'High sodium intake', 'Family history', 'Alcohol'],
      pathophysiology: 'Increased peripheral resistance and/or cardiac output, modulated by RAAS and sympathetic tone, causes end-organ damage over time.',
      presentation: Presentation(
        symptoms: ['Usually asymptomatic', 'Headache (if severe)'],
        signs: ['Elevated BP on repeated measurement', 'Retinal changes', 'LV heave'],
      ),
      redFlags: ['BP >180/120 with end-organ damage (emergency)', 'Acute neuro/cardiac symptoms'],
      workup: Workup(labs: ['BMP', 'Lipids', 'Urinalysis', 'HbA1c'], imaging: ['ECG for LVH'], ecg: null),
      differentials: ['d_aki'],
      criteria: ['Stage 1: ≥130/80; Stage 2: ≥140/90 (ACC/AHA)'],
      management: Management(
        conservative: ['DASH diet', 'Sodium restriction', 'Weight loss', 'Exercise', 'Limit alcohol'],
        medical: ['Thiazide, ACEi/ARB, or CCB first-line', 'Combine for stage 2', 'Compelling indications guide choice'],
        drugIds: ['drug_lisinopril', 'drug_amlodipine', 'drug_hydrochlorothiazide'],
      ),
      prognosis: 'Excellent with control; uncontrolled HTN drives major CV events.',
      complications: ['Stroke', 'MI', 'Heart failure', 'CKD', 'Retinopathy'],
      highYield: ['ACEi/ARB favored in diabetes/CKD', 'Hypertensive emergency needs controlled BP lowering', 'Confirm with out-of-office readings'],
      difficulty: 2,
      evidence: Evidence(citations: [Citation(title: 'ACC/AHA BP Guideline', source: 'Hypertension', year: 2017, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Disease(
      id: 'd_cirrhosis',
      conceptId: 'c_cirrhosis',
      name: 'Cirrhosis',
      icd10: ['K74'],
      specialty: ['Hepatology', 'Gastroenterology'],
      system: BodySystem.gastrointestinal,
      summary: 'Diffuse hepatic fibrosis with regenerative nodules causing portal hypertension and impaired synthetic function.',
      etiology: 'Alcohol, viral hepatitis, MASLD (NAFLD), autoimmune, hemochromatosis.',
      riskFactors: ['Alcohol use', 'Chronic hepatitis B/C', 'Obesity/metabolic syndrome'],
      pathophysiology: 'Chronic injury → stellate-cell activation and fibrosis → increased intrahepatic resistance, portal hypertension and shunting.',
      presentation: Presentation(
        symptoms: ['Fatigue', 'Abdominal distension', 'Easy bruising', 'Confusion (encephalopathy)'],
        signs: ['Jaundice', 'Ascites', 'Spider angiomata', 'Palmar erythema', 'Asterixis'],
      ),
      redFlags: ['Variceal bleeding', 'Hepatic encephalopathy', 'Spontaneous bacterial peritonitis'],
      workup: Workup(labs: ['LFTs', 'Albumin', 'INR', 'Platelets', 'Bilirubin'], imaging: ['Ultrasound', 'Elastography']),
      differentials: ['d_chf'],
      criteria: ['MELD and Child-Pugh stratify severity'],
      management: Management(
        conservative: ['Abstain from alcohol', 'Treat underlying cause', 'Vaccinate', 'Nutrition'],
        medical: ['Diuretics for ascites', 'Beta-blocker for varices', 'Lactulose/rifaximin for encephalopathy'],
        surgical: ['TIPS for refractory ascites/varices', 'Liver transplantation'],
        drugIds: ['drug_furosemide'],
      ),
      prognosis: 'Compensated cirrhosis can be stable for years; decompensation worsens survival markedly.',
      complications: ['Variceal hemorrhage', 'Ascites/SBP', 'Encephalopathy', 'Hepatocellular carcinoma'],
      highYield: ['MELD predicts mortality / transplant priority', 'AST:ALT ≥2 suggests alcohol', 'Screen for HCC and varices'],
      difficulty: 4,
      evidence: Evidence(citations: [Citation(title: 'AASLD Practice Guidance', source: 'Hepatology', year: 2021, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.b),
    ),
  ];

  static Disease? byId(String id) {
    for (final d in all) {
      if (d.id == id) return d;
    }
    return null;
  }
}
