import 'package:synapse_core/synapse_core.dart';

/// The seed Drug Bank (prompt 46): drugs + a normalized class layer + an
/// interaction graph powering the checker. Educational content only.
class DrugsSeed {
  const DrugsSeed._();

  /// Pharmacology concepts these drugs anchor to (merged by the repository).
  static const List<Concept> concepts = [
    Concept(id: 'c_beta_blocker', name: 'Beta-blockers', aliases: ['β-blocker'], domain: ConceptDomain.pharmacology, summary: 'Block β-adrenergic receptors → ↓HR, ↓contractility, ↓renin.'),
    Concept(id: 'c_acei', name: 'ACE inhibitors', aliases: ['ACEi'], domain: ConceptDomain.pharmacology, summary: 'Block conversion of angiotensin I→II; afterload reduction, renoprotection.'),
    Concept(id: 'c_ccb', name: 'Calcium channel blockers', aliases: ['CCB'], domain: ConceptDomain.pharmacology, summary: 'Block L-type calcium channels → vasodilation / negative chronotropy.'),
    Concept(id: 'c_diuretic', name: 'Diuretics', domain: ConceptDomain.pharmacology, summary: 'Increase renal sodium and water excretion.'),
    Concept(id: 'c_statin', name: 'Statins', aliases: ['HMG-CoA reductase inhibitors'], domain: ConceptDomain.pharmacology, summary: 'Inhibit HMG-CoA reductase → ↓LDL, plaque stabilization.'),
    Concept(id: 'c_anticoagulant', name: 'Anticoagulants', domain: ConceptDomain.pharmacology, summary: 'Reduce clot formation via the coagulation cascade.'),
    Concept(id: 'c_antiplatelet', name: 'Antiplatelets', domain: ConceptDomain.pharmacology, summary: 'Inhibit platelet aggregation (e.g. COX-1, P2Y12).'),
    Concept(id: 'c_macrolide', name: 'Macrolides', domain: ConceptDomain.pharmacology, summary: 'Bind the 50S ribosomal subunit; cover atypicals; QT/CYP3A4 effects.'),
    Concept(id: 'c_corticosteroid', name: 'Corticosteroids', aliases: ['glucocorticoids'], domain: ConceptDomain.pharmacology, summary: 'Broad anti-inflammatory/immunosuppressive effects.'),
    Concept(id: 'c_bronchodilator', name: 'Bronchodilators', domain: ConceptDomain.pharmacology, summary: 'Relax airway smooth muscle (β2-agonists, antimuscarinics).'),
    Concept(id: 'c_insulin', name: 'Insulin', domain: ConceptDomain.pharmacology, summary: 'Anabolic hormone lowering glucose by cellular uptake.'),
    Concept(id: 'c_biguanide', name: 'Biguanides', domain: ConceptDomain.pharmacology, summary: 'Reduce hepatic gluconeogenesis and improve insulin sensitivity.'),
    Concept(id: 'c_glycopeptide', name: 'Glycopeptides', domain: ConceptDomain.pharmacology, summary: 'Inhibit gram-positive cell-wall synthesis (vancomycin).'),
  ];

  static const List<DrugClass> classes = [
    DrugClass(id: 'class_beta_blocker', name: 'Beta-blockers', conceptId: 'c_beta_blocker', system: BodySystem.cardiovascular, summary: 'Antagonize β-adrenergic receptors.', classEffects: ['↓Heart rate', '↓Contractility', 'Bronchospasm (non-selective)', 'Mask hypoglycemia'], memberIds: ['drug_metoprolol']),
    DrugClass(id: 'class_acei', name: 'ACE inhibitors', conceptId: 'c_acei', system: BodySystem.cardiovascular, summary: 'Inhibit angiotensin-converting enzyme.', classEffects: ['Afterload reduction', 'Renoprotection', 'Dry cough', 'Hyperkalemia', 'Angioedema'], memberIds: ['drug_lisinopril']),
    DrugClass(id: 'class_ccb', name: 'Calcium channel blockers', conceptId: 'c_ccb', system: BodySystem.cardiovascular, summary: 'Block L-type calcium channels.', classEffects: ['Vasodilation', 'Peripheral edema', 'Negative chronotropy (non-DHP)'], memberIds: ['drug_amlodipine']),
    DrugClass(id: 'class_thiazide', name: 'Thiazide diuretics', conceptId: 'c_diuretic', system: BodySystem.renal, summary: 'Inhibit Na-Cl cotransporter in the distal tubule.', classEffects: ['Hypokalemia', 'Hyponatremia', 'Hyperuricemia', 'Hyperglycemia'], memberIds: ['drug_hydrochlorothiazide']),
    DrugClass(id: 'class_loop', name: 'Loop diuretics', conceptId: 'c_diuretic', system: BodySystem.renal, summary: 'Inhibit Na-K-2Cl in the thick ascending limb.', classEffects: ['Potent diuresis', 'Hypokalemia', 'Ototoxicity'], memberIds: ['drug_furosemide']),
    DrugClass(id: 'class_statin', name: 'Statins', conceptId: 'c_statin', system: BodySystem.cardiovascular, summary: 'HMG-CoA reductase inhibitors.', classEffects: ['↓LDL', 'Myopathy', 'Transaminitis'], memberIds: ['drug_atorvastatin']),
    DrugClass(id: 'class_doac', name: 'Direct oral anticoagulants', conceptId: 'c_anticoagulant', system: BodySystem.hematology, summary: 'Direct factor Xa / thrombin inhibitors.', classEffects: ['Anticoagulation', 'Bleeding', 'No routine monitoring'], memberIds: ['drug_apixaban']),
    DrugClass(id: 'class_vka', name: 'Vitamin K antagonists', conceptId: 'c_anticoagulant', system: BodySystem.hematology, summary: 'Inhibit vitamin-K-dependent factor synthesis.', classEffects: ['Anticoagulation', 'Narrow therapeutic index', 'Many interactions'], memberIds: ['drug_warfarin']),
    DrugClass(id: 'class_antiplatelet', name: 'Antiplatelets', conceptId: 'c_antiplatelet', system: BodySystem.hematology, summary: 'Inhibit platelet activation/aggregation.', classEffects: ['↓Thrombosis', 'Bleeding', 'GI irritation'], memberIds: ['drug_aspirin']),
    DrugClass(id: 'class_penicillin', name: 'Penicillins', conceptId: 'c_beta_lactam', system: BodySystem.infectious, summary: 'β-lactams inhibiting cell-wall synthesis.', classEffects: ['Bactericidal', 'Hypersensitivity', 'Diarrhea'], memberIds: ['drug_amoxicillin', 'drug_piptazo']),
    DrugClass(id: 'class_macrolide', name: 'Macrolides', conceptId: 'c_macrolide', system: BodySystem.infectious, summary: '50S ribosomal inhibitors.', classEffects: ['Atypical coverage', 'QT prolongation', 'CYP3A4 inhibition'], memberIds: ['drug_azithromycin']),
    DrugClass(id: 'class_glucocorticoid', name: 'Glucocorticoids', conceptId: 'c_corticosteroid', system: BodySystem.endocrine, summary: 'Synthetic corticosteroids.', classEffects: ['Anti-inflammatory', 'Hyperglycemia', 'Immunosuppression', 'Osteoporosis'], memberIds: ['drug_prednisone']),
    DrugClass(id: 'class_saba', name: 'Short-acting β2-agonists', conceptId: 'c_bronchodilator', system: BodySystem.respiratory, summary: 'Rapid airway smooth-muscle relaxation.', classEffects: ['Bronchodilation', 'Tremor', 'Tachycardia', 'Hypokalemia'], memberIds: ['drug_albuterol']),
    DrugClass(id: 'class_insulin', name: 'Insulins', conceptId: 'c_insulin', system: BodySystem.endocrine, summary: 'Exogenous insulin preparations.', classEffects: ['Glucose lowering', 'Hypoglycemia', 'Weight gain'], memberIds: ['drug_insulin']),
    DrugClass(id: 'class_biguanide', name: 'Biguanides', conceptId: 'c_biguanide', system: BodySystem.endocrine, summary: 'First-line oral antidiabetic.', classEffects: ['↓Hepatic glucose', 'GI upset', 'Lactic acidosis (rare)'], memberIds: ['drug_metformin']),
    DrugClass(id: 'class_glycopeptide', name: 'Glycopeptides', conceptId: 'c_glycopeptide', system: BodySystem.infectious, summary: 'Gram-positive cell-wall inhibitors.', classEffects: ['MRSA coverage', 'Nephrotoxicity', 'Red-man syndrome'], memberIds: ['drug_vancomycin']),
  ];

  static final List<Drug> all = [
    Drug(
      id: 'drug_metoprolol', conceptId: 'c_beta_blocker', genericName: 'Metoprolol', brandNames: ['Lopressor', 'Toprol-XL'], classIds: ['class_beta_blocker'],
      mechanism: 'Selective β1-adrenergic antagonist → reduced heart rate, contractility and AV conduction.',
      indications: ['Hypertension', 'Angina', 'Heart failure (succinate)', 'Rate control in AF'], indicationDiseaseIds: ['d_htn', 'd_chf', 'd_afib'],
      dosing: Dosing(adult: '25–100 mg PO BID (tartrate); titrate', renal: 'No adjustment', hepatic: 'Reduce dose'),
      routes: ['PO', 'IV'], pk: Pharmacokinetics(metabolism: 'Hepatic CYP2D6', halfLife: '3–7 h'),
      contraindications: ['Decompensated heart failure', 'Severe bradycardia', 'High-degree AV block'],
      cautions: ['Asthma/COPD (β1-selective but caution)', 'Diabetes (masks hypoglycemia)'],
      adverse: AdverseEffects(common: ['Fatigue', 'Bradycardia', 'Cold extremities'], serious: ['Heart block', 'Bronchospasm']),
      monitoring: ['Heart rate', 'Blood pressure'], highYield: ['Avoid abrupt withdrawal (rebound)', 'Use succinate for HFrEF'],
      difficulty: 3, evidence: Evidence(citations: [Citation(title: 'Goodman & Gilman', source: 'Pharmacology', type: CitationType.textbook)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_lisinopril', conceptId: 'c_acei', genericName: 'Lisinopril', brandNames: ['Prinivil', 'Zestril'], classIds: ['class_acei'],
      mechanism: 'Inhibits ACE → ↓angiotensin II and aldosterone → vasodilation and natriuresis.',
      indications: ['Hypertension', 'Heart failure', 'Diabetic nephropathy', 'Post-MI'], indicationDiseaseIds: ['d_htn', 'd_chf'],
      dosing: Dosing(adult: '10–40 mg PO daily', renal: 'Reduce; monitor K+/Cr', hepatic: 'No adjustment'),
      routes: ['PO'], pk: Pharmacokinetics(excretion: 'Renal', halfLife: '12 h'),
      contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'History of angioedema'],
      cautions: ['Hyperkalemia', 'Acute kidney injury', 'Hypotension'],
      adverse: AdverseEffects(common: ['Dry cough', 'Dizziness', 'Hyperkalemia'], serious: ['Angioedema', 'Acute renal failure']),
      monitoring: ['Potassium', 'Creatinine', 'Blood pressure'],
      interactions: [DrugInteraction(withDrugId: 'drug_hydrochlorothiazide', severity: InteractionSeverity.minor, effect: 'Additive BP lowering — often used together; monitor for hypotension', mechanism: 'Complementary mechanisms')],
      highYield: ['Stop in pregnancy', 'Dry cough → switch to ARB', 'Check K+/Cr after starting'],
      difficulty: 3, evidence: Evidence(citations: [Citation(title: 'ACC/AHA BP Guideline', source: 'Hypertension', year: 2017, type: CitationType.guideline)], levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_amlodipine', conceptId: 'c_ccb', genericName: 'Amlodipine', brandNames: ['Norvasc'], classIds: ['class_ccb'],
      mechanism: 'Dihydropyridine CCB → peripheral arterial vasodilation.',
      indications: ['Hypertension', 'Angina'], indicationDiseaseIds: ['d_htn'],
      dosing: Dosing(adult: '5–10 mg PO daily'), routes: ['PO'], pk: Pharmacokinetics(halfLife: '30–50 h', metabolism: 'Hepatic CYP3A4'),
      contraindications: ['Severe aortic stenosis'], cautions: ['Hepatic impairment'],
      adverse: AdverseEffects(common: ['Peripheral edema', 'Flushing', 'Headache'], serious: ['Reflex tachycardia']),
      monitoring: ['Blood pressure', 'Edema'], highYield: ['Edema is dose-related, not fluid overload'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_hydrochlorothiazide', conceptId: 'c_diuretic', genericName: 'Hydrochlorothiazide', brandNames: ['Microzide', 'HCTZ'], classIds: ['class_thiazide'],
      mechanism: 'Inhibits the Na-Cl cotransporter in the distal convoluted tubule.',
      indications: ['Hypertension', 'Edema'], indicationDiseaseIds: ['d_htn'],
      dosing: Dosing(adult: '12.5–25 mg PO daily'), routes: ['PO'], pk: Pharmacokinetics(halfLife: '6–15 h'),
      contraindications: ['Anuria', 'Sulfa allergy (caution)'], cautions: ['Gout', 'Diabetes'],
      adverse: AdverseEffects(common: ['Hypokalemia', 'Hyponatremia', 'Hyperuricemia'], serious: ['Severe electrolyte disturbance']),
      monitoring: ['Electrolytes', 'Uric acid', 'Glucose'], highYield: ['Hyper-GLUC: glucose, lipids, uric acid, calcium'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_furosemide', conceptId: 'c_diuretic', genericName: 'Furosemide', brandNames: ['Lasix'], classIds: ['class_loop'],
      mechanism: 'Inhibits Na-K-2Cl in the thick ascending limb → potent diuresis.',
      indications: ['Heart failure (congestion)', 'Edema', 'AKI volume overload'], indicationDiseaseIds: ['d_chf', 'd_aki', 'd_cirrhosis'],
      dosing: Dosing(adult: '20–80 mg PO/IV; titrate to effect', renal: 'Higher doses needed'),
      routes: ['PO', 'IV'], pk: Pharmacokinetics(halfLife: '1–2 h', excretion: 'Renal'),
      contraindications: ['Anuria'], cautions: ['Hypovolemia', 'Sulfa allergy'],
      adverse: AdverseEffects(common: ['Hypokalemia', 'Hypovolemia'], serious: ['Ototoxicity (rapid IV)', 'AKI']),
      monitoring: ['Electrolytes', 'Renal function', 'Weight/urine output'], highYield: ['IV is ~2× as potent as PO', 'Watch potassium'],
      difficulty: 3, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_atorvastatin', conceptId: 'c_statin', genericName: 'Atorvastatin', brandNames: ['Lipitor'], classIds: ['class_statin'],
      mechanism: 'Inhibits HMG-CoA reductase → ↓cholesterol synthesis, ↑LDL receptors.',
      indications: ['Hyperlipidemia', 'ASCVD prevention', 'Post-MI/stroke'], indicationDiseaseIds: ['d_stemi', 'd_stroke'],
      dosing: Dosing(adult: '10–80 mg PO daily', hepatic: 'Contraindicated in active disease'),
      routes: ['PO'], pk: Pharmacokinetics(metabolism: 'CYP3A4', halfLife: '14 h'),
      contraindications: ['Active liver disease', 'Pregnancy'], cautions: ['Concurrent CYP3A4 inhibitors'],
      adverse: AdverseEffects(common: ['Myalgia', 'GI upset'], serious: ['Rhabdomyolysis', 'Hepatotoxicity']),
      monitoring: ['LFTs at baseline', 'CK if symptomatic'],
      interactions: [DrugInteraction(withClassId: 'class_macrolide', severity: InteractionSeverity.moderate, effect: 'Increased statin levels → myopathy risk', mechanism: 'CYP3A4 inhibition')],
      highYield: ['High-intensity statin after ACS/stroke', 'Stop if myopathy + ↑CK'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_aspirin', conceptId: 'c_antiplatelet', genericName: 'Aspirin', brandNames: ['ASA', 'Bayer'], classIds: ['class_antiplatelet'],
      mechanism: 'Irreversibly inhibits COX-1 → ↓thromboxane A2 → ↓platelet aggregation.',
      indications: ['ACS', 'Secondary CV prevention', 'Ischemic stroke'], indicationDiseaseIds: ['d_stemi', 'd_stroke'],
      dosing: Dosing(adult: '81 mg daily (prevention); 162–325 mg load in ACS'),
      routes: ['PO'], pk: Pharmacokinetics(halfLife: 'Dose-dependent'),
      contraindications: ['Active bleeding', 'Aspirin allergy', 'Children with viral illness (Reye)'],
      cautions: ['Peptic ulcer disease', 'Asthma (sensitivity)'],
      adverse: AdverseEffects(common: ['GI irritation', 'Bruising'], serious: ['GI bleed', 'Hemorrhagic stroke']),
      monitoring: ['Signs of bleeding'],
      interactions: [
        DrugInteraction(withDrugId: 'drug_warfarin', severity: InteractionSeverity.major, effect: 'Markedly increased bleeding risk', mechanism: 'Additive hemostatic impairment'),
        DrugInteraction(withDrugId: 'drug_apixaban', severity: InteractionSeverity.major, effect: 'Increased bleeding risk', mechanism: 'Additive antithrombotic effect'),
      ],
      highYield: ['Loading dose in ACS', 'Avoid in Reye-risk children'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_warfarin', conceptId: 'c_anticoagulant', genericName: 'Warfarin', brandNames: ['Coumadin'], classIds: ['class_vka'],
      mechanism: 'Inhibits vitamin K epoxide reductase → ↓factors II, VII, IX, X.',
      indications: ['AF (valvular)', 'VTE', 'Mechanical valves'], indicationDiseaseIds: ['d_afib', 'd_pe'],
      dosing: Dosing(adult: 'Individualized to INR (target 2–3)'),
      routes: ['PO'], pk: Pharmacokinetics(metabolism: 'CYP2C9', halfLife: '20–60 h'),
      contraindications: ['Pregnancy', 'Active bleeding'], cautions: ['Many drug/food interactions', 'Fall risk'],
      adverse: AdverseEffects(common: ['Bruising'], serious: ['Major hemorrhage', 'Skin necrosis (early)']),
      monitoring: ['INR'], antidote: 'Vitamin K; 4-factor PCC for major bleeding',
      interactions: [
        DrugInteraction(withDrugId: 'drug_aspirin', severity: InteractionSeverity.major, effect: 'Markedly increased bleeding', mechanism: 'Additive'),
        DrugInteraction(withDrugId: 'drug_azithromycin', severity: InteractionSeverity.moderate, effect: 'Elevated INR / bleeding', mechanism: 'Altered gut flora + CYP effects'),
        DrugInteraction(withDrugId: 'drug_amoxicillin', severity: InteractionSeverity.moderate, effect: 'Possible INR elevation', mechanism: 'Gut flora disruption'),
      ],
      highYield: ['Bridge with heparin when starting (early procoagulant)', 'Vitamin K reverses'],
      difficulty: 4, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_apixaban', conceptId: 'c_anticoagulant', genericName: 'Apixaban', brandNames: ['Eliquis'], classIds: ['class_doac'],
      mechanism: 'Direct factor Xa inhibitor.',
      indications: ['Non-valvular AF', 'VTE treatment/prevention'], indicationDiseaseIds: ['d_afib', 'd_pe'],
      dosing: Dosing(adult: '5 mg BID (2.5 mg if ≥2 of: age≥80, weight≤60kg, Cr≥1.5)', renal: 'Dose reduce'),
      routes: ['PO'], pk: Pharmacokinetics(halfLife: '12 h', metabolism: 'CYP3A4/P-gp'),
      contraindications: ['Active bleeding', 'Mechanical valves'], cautions: ['Renal/hepatic impairment'],
      adverse: AdverseEffects(common: ['Bruising'], serious: ['Major bleeding']),
      monitoring: ['Renal function', 'Bleeding'], antidote: 'Andexanet alfa',
      interactions: [DrugInteraction(withDrugId: 'drug_aspirin', severity: InteractionSeverity.major, effect: 'Increased bleeding', mechanism: 'Additive')],
      highYield: ['No routine INR monitoring', 'Preferred over warfarin in non-valvular AF'],
      difficulty: 3, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_amoxicillin', conceptId: 'c_beta_lactam', genericName: 'Amoxicillin', brandNames: ['Amoxil'], classIds: ['class_penicillin'],
      mechanism: 'β-lactam binding penicillin-binding proteins → inhibits cell-wall synthesis.',
      indications: ['CAP (outpatient)', 'Otitis media', 'Strep pharyngitis', 'H. pylori (combo)'], indicationDiseaseIds: ['d_cap'],
      dosing: Dosing(adult: '500–1000 mg PO TID', pediatric: '40–90 mg/kg/day divided', renal: 'Extend interval if severe'),
      routes: ['PO'], pk: Pharmacokinetics(excretion: 'Renal', halfLife: '1 h'),
      contraindications: ['Penicillin anaphylaxis'], cautions: ['Mononucleosis (rash)'],
      adverse: AdverseEffects(common: ['Diarrhea', 'Rash'], serious: ['Anaphylaxis', 'C. difficile colitis']),
      monitoring: ['Allergic reaction'], highYield: ['First-line for outpatient CAP', 'Amoxicillin rash in EBV'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_azithromycin', conceptId: 'c_macrolide', genericName: 'Azithromycin', brandNames: ['Zithromax', 'Z-Pak'], classIds: ['class_macrolide'],
      mechanism: 'Binds 50S ribosomal subunit → inhibits protein synthesis.',
      indications: ['Atypical pneumonia', 'Pertussis', 'Chlamydia', 'COPD exacerbation'], indicationDiseaseIds: ['d_cap'],
      dosing: Dosing(adult: '500 mg day 1, then 250 mg ×4 days'), routes: ['PO', 'IV'], pk: Pharmacokinetics(halfLife: '68 h (long tissue)'),
      contraindications: ['History of cholestatic jaundice with macrolides'], cautions: ['QT prolongation'],
      adverse: AdverseEffects(common: ['GI upset'], serious: ['QT prolongation', 'Torsades']),
      monitoring: ['QT if risk factors'],
      interactions: [
        DrugInteraction(withDrugId: 'drug_warfarin', severity: InteractionSeverity.moderate, effect: 'Elevated INR', mechanism: 'Gut flora + metabolism'),
        DrugInteraction(withClassId: 'class_statin', severity: InteractionSeverity.moderate, effect: 'Increased statin myopathy risk', mechanism: 'CYP3A4'),
      ],
      highYield: ['Covers atypicals', 'Watch QT with other QT drugs'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_albuterol', conceptId: 'c_bronchodilator', genericName: 'Albuterol', brandNames: ['Ventolin', 'ProAir', 'salbutamol'], classIds: ['class_saba'],
      mechanism: 'Short-acting β2-agonist → airway smooth-muscle relaxation.',
      indications: ['Asthma', 'COPD', 'Bronchospasm', 'Hyperkalemia (adjunct)'], indicationDiseaseIds: ['d_asthma', 'd_copd'],
      dosing: Dosing(adult: '2 puffs q4–6h PRN; nebulized in exacerbation'),
      routes: ['Inhaled', 'Nebulized'], pk: Pharmacokinetics(halfLife: '4–6 h'),
      contraindications: ['Hypersensitivity'], cautions: ['Tachyarrhythmia', 'Hyperthyroidism'],
      adverse: AdverseEffects(common: ['Tremor', 'Tachycardia', 'Palpitations'], serious: ['Hypokalemia', 'Paradoxical bronchospasm']),
      monitoring: ['Symptom control', 'Inhaler frequency'], highYield: ['Reliever, not controller', 'Frequent use signals poor control'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_prednisone', conceptId: 'c_corticosteroid', genericName: 'Prednisone', brandNames: ['Deltasone'], classIds: ['class_glucocorticoid'],
      mechanism: 'Synthetic glucocorticoid → broad anti-inflammatory/immunosuppressive effects.',
      indications: ['Asthma/COPD exacerbation', 'Autoimmune disease', 'Allergic reaction'], indicationDiseaseIds: ['d_asthma', 'd_copd'],
      dosing: Dosing(adult: '40 mg PO daily (typical exacerbation burst)'),
      routes: ['PO'], pk: Pharmacokinetics(halfLife: '2–4 h (biologic longer)'),
      contraindications: ['Systemic fungal infection'], cautions: ['Diabetes', 'Infection', 'Peptic ulcer'],
      adverse: AdverseEffects(common: ['Hyperglycemia', 'Insomnia', 'Increased appetite', 'Mood change'], serious: ['Adrenal suppression', 'Osteoporosis', 'Immunosuppression']),
      monitoring: ['Glucose', 'Blood pressure', 'Bone health (chronic)'],
      interactions: [DrugInteraction(withDrugId: 'drug_insulin', severity: InteractionSeverity.moderate, effect: 'Reduced glycemic control', mechanism: 'Steroid-induced hyperglycemia')],
      highYield: ['Taper if prolonged course', 'Stress-dose if chronic use'],
      difficulty: 3, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_insulin', conceptId: 'c_insulin', genericName: 'Insulin', brandNames: ['Humalog', 'Lantus', 'Novolog'], classIds: ['class_insulin'],
      mechanism: 'Exogenous insulin → cellular glucose uptake, ↓hepatic gluconeogenesis.',
      indications: ['Type 1 diabetes', 'Type 2 (when needed)', 'DKA/HHS', 'Hyperkalemia (with glucose)'], indicationDiseaseIds: ['d_dka', 'd_t2dm'],
      dosing: Dosing(adult: 'Highly individualized; basal-bolus or infusion'),
      routes: ['SC', 'IV (regular)'], pk: Pharmacokinetics(halfLife: 'Preparation-dependent'),
      contraindications: ['Hypoglycemia'], cautions: ['Renal impairment (↓clearance)'],
      adverse: AdverseEffects(common: ['Hypoglycemia', 'Weight gain'], serious: ['Severe hypoglycemia', 'Hypokalemia']),
      monitoring: ['Glucose', 'Potassium (in DKA)'], antidote: 'Dextrose (IV) / glucagon for hypoglycemia',
      highYield: ['Only IV insulin uses regular', 'Shifts K+ intracellularly'],
      difficulty: 3, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_metformin', conceptId: 'c_biguanide', genericName: 'Metformin', brandNames: ['Glucophage'], classIds: ['class_biguanide'],
      mechanism: 'Reduces hepatic gluconeogenesis and improves peripheral insulin sensitivity.',
      indications: ['Type 2 diabetes (first-line)', 'PCOS'], indicationDiseaseIds: ['d_t2dm'],
      dosing: Dosing(adult: '500 mg daily, titrate to 2000 mg/day', renal: 'Avoid if eGFR < 30'),
      routes: ['PO'], pk: Pharmacokinetics(excretion: 'Renal (unchanged)', halfLife: '6 h'),
      contraindications: ['eGFR < 30', 'Severe hepatic disease'], cautions: ['Hold before iodinated contrast', 'Acute illness'],
      adverse: AdverseEffects(common: ['Diarrhea', 'Nausea', 'Metallic taste'], serious: ['Lactic acidosis (rare)', 'B12 deficiency']),
      monitoring: ['Renal function', 'B12 (long-term)'], highYield: ['First-line in T2DM', 'No hypoglycemia as monotherapy', 'Hold for contrast/AKI'],
      difficulty: 2, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_vancomycin', conceptId: 'c_glycopeptide', genericName: 'Vancomycin', brandNames: ['Vancocin'], classIds: ['class_glycopeptide'],
      mechanism: 'Inhibits gram-positive cell-wall synthesis by binding D-Ala-D-Ala.',
      indications: ['MRSA', 'Severe gram-positive infection', 'C. difficile (oral)'], indicationDiseaseIds: ['d_sepsis'],
      dosing: Dosing(adult: 'Weight-based IV with level/AUC monitoring; 125 mg PO QID for C. diff', renal: 'Adjust by levels'),
      routes: ['IV', 'PO (gut only)'], pk: Pharmacokinetics(excretion: 'Renal', halfLife: '4–6 h'),
      contraindications: ['Hypersensitivity'], cautions: ['Renal impairment', 'Concurrent nephrotoxins'],
      adverse: AdverseEffects(common: ['Red-man syndrome (rate-related)'], serious: ['Nephrotoxicity', 'Ototoxicity']),
      monitoring: ['Trough/AUC levels', 'Renal function'], highYield: ['Oral vanc only for C. diff (not absorbed)', 'Red-man = infusion-rate reaction, not allergy'],
      difficulty: 4, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
    Drug(
      id: 'drug_piptazo', conceptId: 'c_beta_lactam', genericName: 'Piperacillin-tazobactam', brandNames: ['Zosyn'], classIds: ['class_penicillin'],
      mechanism: 'Antipseudomonal penicillin + β-lactamase inhibitor → broad gram-negative/positive/anaerobe coverage.',
      indications: ['Sepsis (empiric)', 'Hospital-acquired pneumonia', 'Intra-abdominal infection'], indicationDiseaseIds: ['d_sepsis'],
      dosing: Dosing(adult: '3.375–4.5 g IV q6–8h (extended infusion)', renal: 'Dose reduce'),
      routes: ['IV'], pk: Pharmacokinetics(excretion: 'Renal', halfLife: '1 h'),
      contraindications: ['Penicillin anaphylaxis'], cautions: ['Renal impairment', 'Concurrent vancomycin (AKI)'],
      adverse: AdverseEffects(common: ['Diarrhea', 'Rash'], serious: ['AKI (with vancomycin)', 'C. difficile']),
      monitoring: ['Renal function'], highYield: ['Common empiric sepsis backbone', 'Pip-tazo + vanc raises AKI risk'],
      difficulty: 3, evidence: Evidence(levelOfEvidence: LevelOfEvidence.a),
    ),
  ];

  static Drug? byId(String id) {
    for (final d in all) {
      if (d.id == id) return d;
    }
    return null;
  }

  static DrugClass? classById(String id) {
    for (final c in classes) {
      if (c.id == id) return c;
    }
    return null;
  }
}
